---
- name: Install git
  apt:
    name:
      - git

- name: Clone Browsertrix repo
  git:
    repo: https://github.com/webrecorder/browsertrix-cloud.git
    dest: /root/browsertrix
    version: "{{browsertrix_version}}"
    version: cdefb8d06e98cf0e73083d120bab0b07e0def125
    force: yes
    
- name: Config for Browsertrix
  ansible.builtin.template:
    src: config.env.j2
    dest: /root/browsertrix/configs/config.env
    owner: root
    group: root
    mode: '0644'
  tags: config  

- name: Config for Browsertrix AuthSign
  ansible.builtin.template:
    src: signing.yaml.j2
    dest: /root/browsertrix/configs/signing.yaml
    owner: root
    group: root
    mode: '0644'
  tags: config
  when: authsign_docker == True
    
- name: Move Browsertrix Authsign from port 80 to 81 not to conflict with Nginx
  lineinfile:
    path: /root/browsertrix/docker-compose.yml
    regex: 80:80
    line: "      - 81:80"
  when: authsign_docker == True

- name: Upgrade mongo line
  lineinfile:
    path: /root/browsertrix/docker-compose.yml
    regex: "   command: ['-c', 'mc mb local/test-bucket; mc policy set public local/test-bucket' ]"
    line: "    command: ['-c', 'mc mb local/test-bucket; mc policy set public local/test-bucket' ]"


- name: Expose Browsertrix Authsign port 8080 Browsertrix
  lineinfile:
    path: /root/browsertrix/docker-compose.yml
    line: "      - 127.0.0.1:8080:8080"
    regex: "127.0.0.1:8080:8080"
    insertafter: "      - 81:80"
 
- name: Create Browsertrix data folder
  file:
    path: /mnt/browsertrix
    state: directory

- name: Bind Browsertrix storage volume to created folder
  lineinfile:
    path: /root/browsertrix/docker-compose.yml
    regex: btrix-minio-data:/data
    line: "      - /mnt/browsertrix:/data"      

### Enable LOKI Logger Driver and settings
- name: Install LOKI Driver
  shell: "docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"
  when: browsertrix_loki is defined
  ignore_errors: true

- name: Enable Docker-Compose Overrides for Logging
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: /root/browsertrix/docker-compose.override.yml
  when: browsertrix_loki is defined

### Prepeare browstrix contrib folder ##
- name: Create Browsertrix contrib folder
  file:
    path: /root/browsertrix-contrib
    state: directory

- name: Copy over Browsertrix profile
  copy:
    src: "{{browsertrix_profile_file}}"
    dest: /root/browsertrix-contrib/profile.tar.gz
    group: root
    owner: root
    mode: 0555
  when: browsertrix_profile_file is defined

- name: Stop Browsertrix
  command: docker-compose down
  args:
    chdir: /root/browsertrix
  tags: config

- name: Build Stop Browsertrix
  command: docker-compose build
  args:
    chdir: /root/browsertrix
  tags: config

- name: Start Browsertrix
  command: docker-compose up -d
  args:
    chdir: /root/browsertrix
  tags: config

- name: Download latest Browsertrix crawler
  command: docker pull webrecorder/browsertrix-crawler:{{browsertrix_docker['crawler']}}
  args:
    chdir: /root/browsertrix

# Upload the profile used by Browsertrix crawls
- name: Template uploadFile for Browsertrix to install profile
  ansible.builtin.template:
    src: uploadFile.sh
    dest: /root/browsertrix-contrib/uploadFile.sh
    group: root
    owner: root
    mode: 0755

- name: Template createAccount for browsertrix
  copy:
    src: createAccount.py
    dest: /root/browsertrix-contrib/createAccount.py
    group: root
    owner: root
    mode: 0755

- name: Upload profile for Minio
  command: ./uploadFile.sh test-bucket profile.tar.gz
  args:
    chdir: /root/browsertrix-contrib

# Crete accounts and archives
- name: Create master account
  command: "./createAccount.py {{ browsertrix_user_email }} {{ browsertrix_user_password }} MasterArchive"
  args:
    chdir: /root/browsertrix-contrib

